[package]
name = "async_crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["rustls-tls", "gzip", "brotli", "json"] }
scraper = "0.13"
anyhow = "1.0"
dashmap = "5.4"
url = "2.4"
futures = "0.3"
